defaults:
  - experiment: meta_curriculum
  - task: gaussian_2d
  - model: mlp_2d 
  - meta/inner_loop: supervised_curriculum
  - meta/outer_loop: es_supervised
  - optim: base
  - curriculum: base
  - logging: base
  - callbacks: 
    - console_logger
    - noop

seed: 1234

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}